
export const PERMISSIONS = {
  // --- GLOBAL & SPECIAL ---
  ADMIN: "CONFIGURACION ADMINISTRADOR",

  // --- MENU / MODULE LEVEL ---
  MENU: {
    HOME_SELLOUT: "SELLOUT INDURAMA",
    USER_MANAGEMENT: "GESTION USUARIOS",
    CONFIG_PLANTILLAS: "MATRICULACION SELLOUT",
    CARGA_PLANTILLAS: "EXTRACCION SELLOUT",
    MAESTROS: "MAESTROS SELLOUT",
    SIC: "SIC SELLOUT",
    BASE_CONSOLIDADA: "PLANTILLA CONSOLIDADO SELLOUT",
    BASE_NO_HOMOLOGADA: "BASE NO HOMOLOGADA",
    LISTAS_NO_HOMOLOGADOS: "LISTAS NO HOMOLOGADOS",
  },

  // --- INTERNAL MODULE ACTIONS ---

  // Gestión de Usuarios
  USER_MANAGEMENT: {
    USERS: "ACCIONES USUARIO",
    ROLES: "ACCIONES ROLES",
    PERMISSIONS: "ACCIONES PERMISOS",
    DASHBOARD: "DASHBOARD GESTION USUARIOS",
  },

  // Configuración de Plantillas (Matriculación)
  MATRICULACION: {
    CONFIG_CIERRE: "CONFIGURACION CIERRE SELLOUT",
    ACTIONS: "ACCIONES MATRICULACION SELLOUT",
  },

  // Carga de Plantillas (Extracción)
  EXTRACCION: {
    ACTIONS: "ACCIONES CONFIGURACION EXTRACCION",
    CONFIG_EXTRACCION: "CONFIGURACION EXTRACCION",
    DICCIONARIO: "DICCIONARIO",
  },

  // Base no Homologada (No Consolidado)
  BASE_NO_HOMOLOGADA: {
    ALMACENES: "ALMACENES NO HOMOLOGADOS",
    PRODUCTOS: "PRODUCTOS NO HOMOLOGADOS",
  },

  // Listas No Homologados (No Visita)
  LISTAS_NO_HOMOLOGADOS: {
    ALMACENES_NO_VISITA: "ALMACENES NO VISITA",
    PRODUCTOS_OTROS: "PRODUCTOS OTROS",
  }
};
