export const camposMaestrosStores = [
  {
    id: "codeStoreSic",
    headerTitle: "Código SIC",
    type: "number",
    multiline: false,
    rows: 1,
    size: 6,
    placeholder: "Código SIC",
  },
  {
    id: "distributor",
    headerTitle: "Distribuidor",
    type: "text",
    multiline: false,
    rows: 1,
    size: 6,
    placeholder: "Distribuidor",
  },
  {
    id: "storeDistributor",
    headerTitle: "Almacén",
    type: "text",
    multiline: false,
    rows: 1,
    size: 6,
    placeholder: "Almacén",
  },
  {
    id: "searchStore",
    headerTitle: "Búsqueda",
    type: "text",
    multiline: false,
    rows: 1,
    size: 6,
    disabled: true,
    placeholder: "Búsqueda de tienda",
  },
];
