export const COLUMN_KEYWORDS = {
  saleDate: [
    "fecha",
    "dia",
    "mes",
    "anio",
    "año",
    "fecha_dia",
    "fechaventa",
    "venta",
    "date",
    "sale date",
    "fecha_dia",
    "fecha_movimiento",
    "fecha_compte",
    "fecha de contabilizacion",
    "emision",
    "order date",
    "final",
    "fecha sistema",
    "fec.",
    "FECHA DE VENTA",
    "Fecha",
    "fecha_dia",
  ],
  descriptionDistributor: [
    "articulo",
    "producto",
    "descripcion",
    "Descripcion",
    "detalle producto",
    "detalle",
    "item",
    "nombre del producto",
    "codigodescripcion",
    "nomart",
    "descripcion del producto",
    "descripcion distribuidor",
    "descripcion de producto",
    "descripcion producto",
    "descripción producto",
    "descripcionarticulo",
    "descripcion_articulo",
    "nombre del articulo",
    "codigo descripcion",
    "nombre sku",
    "nombre item",
    "nombre producto",
    "modelo",
    "itemname",
    "detalle del producto",
    "des_producto",
    "nombre",
    "articulo indurama",
    "descripcion articulo/servicio",
    "lineas de factura/producto/nombre",
    "articulo o servicio",
    "etiquetas de fila",
    "nombre sku",
    "pro_nombre",
    "despro",
    "productos",
    "expr1005",
    "descripcion articulo/serv.",
  ],

  unitsSoldDistributor: [
    "unidades",
    "cantidad",
    "ventas",
    "total",
    "totales",
    "vendido",
    "vtas",
    "vendidos",
    "units",
    "quantity",
    "uni. vendidas",
    "suma de nombre item",
    "suma de cantidad",
    "ing/egr",
    "2025",
    "sold",
    "unidades vendidas",
    "suma de total general",
    "suma de cant",
    "electrogold",
    "unidades",
    "cantidad ty",
    "suma de unidades venta distribuidor",
    "und",
    "cant",
    "cant.",
    "unidad",
    "vendid",
    "Vta, Período  (u)",
    "seccion",
    "uni vendidas 2025-05",
    "vta, periodo (u)",
    "suma de vta, periodo (u)",
    "suma de cantidad ty",
    "suma de unidades",
    "suma de valor",
    "valor",
    "can",
    "canti",
    "can_fac",
    "cuenta de articulo",
    "Descripcion de Producto",
    "unidades venta distribuidor",
    "suma de ing/egr",
    "total general",
  ],
  codeProductDistributor: [
    "sap",
    "codigo",
    "cod p",
    "código",
    "code",
    "codigo producto",
    "codigo de producto",
    "cod articulo",
    "cod_producto",
    "pro_codigo",
    "modelo",
    "cod. promart",
    "referencia",
    "numero de articulo",
    "cod. catalogo",
    "cob_ite",
    "cod.prod distribuidor",
  ],
  distributor: ["distribuidor", "formato"],
  codeStoreDistributor: [
    "agencia",
    "local",
    "sucursal",
    "locales",
    "cod almacen",
    "almacen",
    "centro",
    "descripcion_agencia",
    "tienda",
    "atributo",
    "alm_nombre",
    "bodega",
    "nombre de serie",
    "nomlocal",
    "cod.almacen distribuidor",
    "AGENCIA",
    "nombre pos",
    "tienda dynamics",
  ],
  saleDay: ["dia", "día"],
  saleMonth: ["mes", "periodo mes"],
  saleYear: ["año", "anio", "periodo año", "periodo anio"],
};

export const PALABRAS_INVALIDAS = [
  "cliente",
  "subtotal",
  "iva",
  "total",
  "datos",
  "producto",
  "vendedor",
  "dirección",
  "ruc",
  "dni",
  "pedido",
  "venta",
  "pago",
  "notas",
  "forma",
  "desde",
  "hasta",
  "orden",
  "fecha",
  "envío",
  "reporte",
  "(en blanco)",
  "local",
  "bodega",
  "almacen",
  "sucursal",
];

export const CAMPOS_CONFIG_ESTANDAR = [
  {
    id: "hojaInicio",
    headerTitle: "Inicio",
    type: "number",
    multiline: false,
    rows: 1,
    size: 1.5,
    placeholder: "Inicio/extracción",
  },
  {
    id: "hojaFin",
    headerTitle: "Fin",
    type: "number",
    multiline: false,
    rows: 1,
    size: 1.5,
    placeholder: "Fin Extracción",
  },
];

export const NOMBRES_CAMPOS = {
  saleDate: "FECHA",
  distributor: "DISTRIBUIDOR",
  codeStoreDistributor: "CÓDIGO DE ALMACÉN",
  codeProductDistributor: "CÓDIGO DE PRODUCTO",
  descriptionDistributor: "PRODUCTO",
  unitsSoldDistributor: "UNIDADES VENDIDAS",
};

export const etiquetasColumnas = {
  saleDate: "Fecha",
  distributor: "Distribuidor",
  codeStoreDistributor: "Almacén",
  codeProductDistributor: "Código producto",
  descriptionDistributor: "Detalle producto",
  unitsSoldDistributor: "Cantidad",
};

export const columnsMatriculacion = [
  {
    id: "distributor",
    label: "Distribuidor",
    field: "distributor",
  },
  {
    id: "storeName",
    label: "Almacén",
    field: "storeName",
  },
  {
    id: "createdAt",
    label: "Fecha de registro",
    field: "calculateDate",
  },
  {
    id: "isUploaded",
    label: "Cargado",
    field: "isUploaded",
  },
  {
    id: "productCount",
    label: "Unidades Vendidas",
    field: "productCountTotal",
  },
  {
    id: "rowsCount",
    label: "# Filas",
    field: "rowCountTotal",
  },
];

export const optionsMappingToField = [
  { id: "distributor", label: "Distribuidor" },
  { id: "codeStoreDistributor", label: "Código de almacén" },
  { id: "codeProductDistributor", label: "Código de producto" },
  { id: "descriptionDistributor", label: "Detalle producto" },
  { id: "unitsSoldDistributor", label: "Cantidad" },
  { id: "saleDate", label: "Fecha" },
  { id: "saleDay", label: "Día" },
  { id: "saleMonth", label: "Mes" },
  { id: "saleYear", label: "Año" },
];

export const styles = {
  container: {
    p: 2,
    borderRadius: 2,
    backgroundColor: "#f9f9f9",
  },
  table: {
    borderRadius: 3,
    mt: 1,
  },
  tableCell: {
    backgroundColor: "#eaeaea",
    borderBottom: "1px solid #ffffff",
    minWidth: "20%",
  },
  typography: {
    fontWeight: 500,
    fontSize: "13px",
    color: "#6f6f6f",
    textTransform: "uppercase",
  },
  tableCellDetail: {
    borderBottom: "1px solid #eee",
    fontSize: "13px",
    fontWeight: 400,
    color: "#333",
    wordBreak: "break-word",
  },
  title: {
    fontWeight: 500,
    fontSize: "12px",
    color: "white",
    textAlign: "center",
    textTransform: "uppercase",
    backgroundColor: "details.main",
    borderRadius: 2,
    p: 1,
    minWidth: "20%",
  },
};

export const isClosed = (closingDate) => {
  const hoy = new Date();
  const cierre = new Date(closingDate);

  hoy.setHours(0, 0, 0, 0);
  cierre.setHours(0, 0, 0, 0);

  const cierreMasUno = new Date(cierre);
  cierreMasUno.setDate(cierreMasUno.getDate() + 2);

  return hoy >= cierreMasUno ? "Cerrado ⛔" : "Abierto 🟢";
};
