import { PERMISSIONS } from "../../constants/permissions";

export const menuSelloutPage = [
  // Fase 1: Configuración
  {
    id: 2,
    name: "Configuración mes",
    icon: "mui:Event",
    visible: true,
    name_server: PERMISSIONS.MENU.CONFIG_PLANTILLAS,
    menuSellout: true,
    nameInfo: "Activa periodos de carga",
    phase: 1,
    phaseName: "Configuración",
    badge: "Fase 1",
    num: "1",
    order: 1,
  },
  {
    id: 2,
    name: "Matriculación Plantillas",
    icon: "mui:TableChart",
    visible: true,
    name_server: PERMISSIONS.MENU.CONFIG_PLANTILLAS,
    menuSellout: true,
    nameInfo: "Listado de clientes a cargar",
    phase: 1,
    phaseName: "Configuración",
    tab: 1,
    num: "2",
    order: 2,
  },
  {
    id: 2,
    name: "Seguimiento Carga",
    icon: "mui:Search",
    visible: true,
    name_server: PERMISSIONS.MENU.CONFIG_PLANTILLAS,
    menuSellout: true,
    nameInfo: "Monitorea avance de registros",
    phase: 1,
    phaseName: "Configuración",
    tab: 2,
    num: "3",
    order: 3,
  },
  // Fase 2: Procesamiento
  {
    id: 5,
    name: "Extracción de datos",
    icon: "mui:FilterList",
    visible: true,
    name_server: PERMISSIONS.MENU.CARGA_PLANTILLAS,
    menuSellout: true,
    nameInfo: "Carga de plantillas de clientes",
    phase: 2,
    phaseName: "Procesamiento",
    badge: "Fase 2",
    num: "4",
    order: 4,
  },
  {
    id: 5,
    name: "Configuración Plantilla Específica",
    icon: "mui:Settings",
    visible: true,
    name_server: PERMISSIONS.EXTRACCION.CONFIG_EXTRACCION,
    menuSellout: true,
    nameInfo: "Campos específicos por cliente",
    phase: 2,
    phaseName: "Procesamiento",
    tab: 1,
    secondary: true,
    num: "4.1",
    order: 4.1,
  },
  {
    id: 5,
    name: "Diccionario",
    icon: "mui:MenuBook",
    visible: true,
    name_server: PERMISSIONS.EXTRACCION.DICCIONARIO,
    menuSellout: true,
    nameInfo: "Homologa términos",
    phase: 2,
    phaseName: "Procesamiento",
    tab: 2,
    secondary: true,
    num: "4.2",
    order: 4.2,
  },
  // Fase 3: Validación
  {
    id: 9,
    name: "No homologados",
    icon: "mui:WarningAmber",
    visible: true,
    name_server: PERMISSIONS.MENU.LISTAS_NO_HOMOLOGADOS,
    menuSellout: true,
    nameInfo: "Almacenes y productos no homologados",
    phase: 3,
    phaseName: "Validación",
    badge: "Fase 3",
    num: "5",
    order: 5,
  },
  {
    id: 3,
    name: "Gestionar Maestros",
    icon: "mui:Group",
    visible: true,
    name_server: PERMISSIONS.MENU.MAESTROS,
    menuSellout: true,
    nameInfo: "Almacenes y productos para homologar",
    phase: 3,
    phaseName: "Validación",
    num: "6",
    order: 6,
  },
  {
    id: 11,
    name: "Sincronización DIM",
    icon: "mui:Public",
    visible: true,
    name_server: PERMISSIONS.MENU.SIC,
    menuSellout: true,
    nameInfo: "Datos sistema comercial",
    phase: 3,
    phaseName: "Validación",
    secondary: true,
    num: "6.1",
    order: 6.1,
  },
  {
    id: 6,
    name: "Base Consolidada",
    icon: "mui:StorageOutlined",
    visible: true,
    name_server: PERMISSIONS.MENU.BASE_CONSOLIDADA,
    menuSellout: true,
    nameInfo: "Información sell out homologada",
    phase: 3,
    phaseName: "Validación",
    num: "7",
    order: 7,
  },
];

const initialStateMenu = [
  {
    id: 0,
    name: "Sellout Mercado",
    icon: "mui:Home",
    nameInfo: "Procesos",
    name_server: PERMISSIONS.MENU.HOME_SELLOUT,
    visible: true,
  },

  {
    id: 1,
    name: "Gestión de usuarios",
    icon: "mui:PeopleAltOutlined",
    nameInfo: "Usuarios",
    name_server: PERMISSIONS.MENU.USER_MANAGEMENT,
    visible: true,
  },

  {
    id: 2,
    name: "Configuración",
    icon: "mui:SettingsOutlined",
    visible: true,
    name_server: PERMISSIONS.MENU.CONFIG_PLANTILLAS,
    menuSellout: true,
    nameInfo: "Configuración de cierre",
  },
  {
    id: 5,
    name: "Carga de plantillas",
    icon: "mui:CloudUploadOutlined",
    visible: true,
    name_server: PERMISSIONS.MENU.CARGA_PLANTILLAS,
    menuSellout: true,
    nameInfo: "Carga de archivos excel",
  },
  {
    id: 3,
    name: "Maestros",
    icon: "mui:DnsOutlined",
    visible: true,
    name_server: PERMISSIONS.MENU.MAESTROS,
    menuSellout: true,
    nameInfo: "Almacenes - Productos",
  },
  {
    id: 6,
    name: "Base Consolidada",
    icon: "mui:StorageOutlined",
    visible: true,
    name_server: PERMISSIONS.MENU.BASE_CONSOLIDADA,
    menuSellout: true,
    nameInfo: "Lista de datos",
  },
  {
    id: 9,
    name: "Base no Homologada",
    icon: "mui:ReportProblemOutlined",
    visible: true,
    name_server: PERMISSIONS.MENU.BASE_NO_HOMOLOGADA,
    menuSellout: false,
    nameInfo: "No Homologados",
  },
  {
    id: 10,
    name: "Listas No Homologados",
    icon: "mui:RuleFolderOutlined",
    visible: true,
    name_server: PERMISSIONS.MENU.LISTAS_NO_HOMOLOGADOS,
    menuSellout: false,
    nameInfo: "Listas No Homologados",
  },
  {
    id: 4,
    name: "Listas DAS",
    icon: "mui:StorefrontOutlined",
    visible: true,
    name_server: PERMISSIONS.MENU.SIC,
    menuSellout: true,
    nameInfo: "Almacenes - Productos SIC",
  },
  {
    id: 11,
    name: "Actualización DIM",
    icon: "mui:CloudSyncOutlined",
    visible: true,
    name_server: PERMISSIONS.MENU.ACTUALIZACION_DIM,
    menuSellout: false,
    nameInfo: "Lista de actualizaciones DIM",
  },
];

export default initialStateMenu;
