export const menuSelloutPage = [
  {
    id: 2,
    name: "Matriculación",
    icon: "mui:AddToQueue",
    visible: true,
    name_server: "MATRICULACION SELLOUT",
    menuSellout: true,
    nameInfo: "Lista",
  },
  {
    id: 3,
    name: "Maestros",
    icon: "mui:DataSaverOnOutlined",
    visible: true,
    name_server: "MAESTROS SELLOUT",
    menuSellout: true,
    nameInfo: "Lista de procesos",
  },
  {
    id: 4,
    name: "SIC",
    visible: true,
    name_server: "SIC SELLOUT",
    menuSellout: true,
    nameInfo: "Lista de procesos",
  },
  {
    id: 5,
    name: "Configuración de extracción",
    visible: true,
    name_server: "EXTRACCION SELLOUT",
    menuSellout: true,
    nameInfo: "Lista de procesos",
  },
  {
    id: 5,
    name: "Extracción Sellout",
    visible: true,
    name_server: "EXTRACCION SELLOUT",
    menuSellout: true,
    nameInfo: "Lista de procesos",
  },
  {
    id: 6,
    name: "Base Consolidado",
    visible: true,
    name_server: "PLANTILLA CONSOLIDADO SELLOUT",
    menuSellout: true,
    nameInfo: "Lista de datos",
  },
];

const initialStateMenu = [
  {
    id: 0,
    name: "Sellout - Indurama",
    icon: "mui:Timeline",
    nameInfo: "Procesos",
    name_server: "SELLOUT INDURAMA",
    visible: true,
  },

  {
    id: 1,
    name: "Gestión de usuarios",
    icon: "mui:ManageAccountsOutlined",
    nameInfo: "Usuarios",
    name_server: "GESTION USUARIOS",
    visible: true,
  },

  {
    id: 2,
    name: "Matriculación",
    icon: "mui:AddToQueue",
    visible: true,
    name_server: "MATRICULACION SELLOUT",
    menuSellout: true,
    nameInfo: "Lista de matriculaciones",
  },
  {
    id: 3,
    name: "Maestros",
    icon: "mui:DataSaverOnOutlined",
    visible: true,
    name_server: "MAESTROS SELLOUT",
    menuSellout: true,
    nameInfo: "Lista",
  },
  {
    id: 4,
    name: "SIC",
    icon: "mui:GridView",
    visible: true,
    name_server: "SIC SELLOUT",
    menuSellout: true,
    nameInfo: "Lista de procesos",
  },
  {
    id: 5,
    name: "Extracción Sellout",
    icon: "mui:MenuBook",
    visible: true,
    name_server: "EXTRACCION SELLOUT",
    menuSellout: true,
    nameInfo: "Lista de procesos",
  },
  {
    id: 6,
    name: "Base Consolidado",
    icon: "mui:FilePresentOutlined",
    visible: true,
    name_server: "PLANTILLA CONSOLIDADO SELLOUT",
    menuSellout: true,
    nameInfo: "Lista de datos",
  },
  {
    id: 7,
    name: "Datos Presupuesto Sellout",
    icon: "mui:PointOfSale",
    visible: true,
    name_server: "PRESUPUESTO SELLOUT",
    menuSellout: false,
    nameInfo: "Lista de procesos",
  },
  {
    id: 8,
    name: "Valores",
    icon: "mui:CurrencyExchange",
    visible: true,
    name_server: "VALORES SELLOUT",
    menuSellout: false,
    nameInfo: "Lista de procesos",
  },
  {
    id: 7,
    name: "Base no Homologada",
    icon: "mui:CurrencyExchange",
    visible: true,
    name_server: "",
    menuSellout: false,
    nameInfo: "Lista de procesos",
  },
];

export default initialStateMenu;
