const styles = {
  mainContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    width: "100%",
    backgroundColor: "#F5F6F7",
    height: "100vh",
    overflow: "hidden",
    gap: 1,
  },
  encabezado: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5F6F7",
    marginLeft: 3,
    marginRight: 3,
    flexShrink: 0,
  },
  contentBox: {
    flex: 1,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 4,
    backgroundColor: "#F5F6F7",
    overflow: "hidden",
    ml: 3,
    mr: 3,
    mb: 1,
    mt: 0,
  },
  header: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5F6F7",
    flexShrink: 0,
  },
  footer: {
    display: "flex",
    height: "40px",
    boxShadow: 5,
    backgroundColor: "#F5F6F7",
    justifyContent: "right",
    alignItems: "center",
    flexShrink: 0,
  },
};
export default styles;
