name: Build and Push to OCIR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: api-ind-com-sellout-front

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate commit tag
        run: echo "COMMIT_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to Azure Container Registry
        run: |
          echo "${{ secrets.AZURE_PASSWORD }}" | docker login registryconsensokb.azurecr.io \
          --username "${{ secrets.AZURE_USERNAME }}" \
          --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -t registryconsensokb.azurecr.io/${{ env.PROJECT_NAME }}:${{ env.COMMIT_ID }}-${{ env.CI_JOB_ID }} \
            -t registryconsensokb.azurecr.io/${{ env.PROJECT_NAME }}:latest \
            .

      - name: Push Docker images
        run: |
          docker push registryconsensokb.azurecr.io/${{ env.PROJECT_NAME }}:${{ env.COMMIT_ID }}
